// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_Demo.Models;

namespace WebApi_Demo.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20210727173640_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi_Demo.Models.Students", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Addresss")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenSV")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSV");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
